import {
  BriefcaseBusiness,
  ChartColumnIncreasing,
  ChartNoAxesCombined,
  CircleUser,
  FileChartColumn,
  FileClock,
  Layers,
  LayoutDashboard,
  LayoutDashboardIcon,
  LockKeyholeOpen,
  Mail,
  MailWarning,
  MessageCircleMore,
  ReceiptText,
  Settings,
  TicketsPlane,
  Users,
  Utensils,
  XCircle,
} from "lucide-react";

export const registerFormControls = [
  {
    name: "emp_code",
    label: "Employee Code",
    placeholder: "Enter Your Employee Code",
    componentType: "input",
    type: "number",
    required: true,
  },
  {
    name: "username",
    label: "Username",
    placeholder: "Enter Your Username",
    componentType: "input",
    type: "text",
    required: true,
  },
  {
    name: "first_name",
    label: "First Name",
    placeholder: "Enter Your First Name",
    componentType: "input",
    type: "text",
    required: true,
  },
  {
    name: "last_name",
    label: "Last Name",
    placeholder: "Enter Your Last Name",
    componentType: "input",
    type: "text",
    required: true,
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter Your Email",
    componentType: "input",
    type: "email",
    required: true,
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter Your Password",
    componentType: "input",
    type: "password",
    required: true,
  },
];

export const loginFormControls = [
  {
    name: "username",
    label: "User Name",
    placeholder: "Enter Your User Name",
    componentType: "input",
    type: "text",
    required: true,
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter Your Password",
    componentType: "input",
    type: "password",
    required: true,
  },
];

export const resetPasswordFormControls = [
  {
    name: "old_password",
    label: "Old Password",
    placeholder: "Enter Your Old Password",
    componentType: "input",
    type: "password",
    required: true,
  },
  {
    name: "new_password",
    label: "New Password",
    placeholder: "Enter Your New Password",
    componentType: "input",
    type: "password",
    required: true,
  },
  {
    name: "confirm_password",
    label: "Confirm Password",
    placeholder: "Confirm New Password",
    componentType: "input",
    type: "password",
    required: true,
  },
];

export const SIDEBAR_MENU = {
  employee: [
    {
      id: "dashboard",
      label: "Dashboard",
      path: "/dashboard",
      icon: LayoutDashboard,
    },
    {
      id: "attendance",
      label: "Attendance",
      path: "/attendance",
      icon: FileChartColumn,
    },
    {
      id: "leave",
      label: "Leave",
      path: "/leave",
      icon: TicketsPlane,
      submenu: [
        {
          id: "leave-aplication",
          label: "Leave Application",
          path: "/leave-aplication",
          icon: Mail,
        },
        {
          id: "leave-history",
          label: "Leave History",
          path: "/leave-history",
          icon: FileClock,
        },
      ],
    },
    {
      id: "meal",
      label: "Meal",
      path: "/meal",
      icon: Utensils,
      submenu: [
        {
          id: "weekly-menu",
          label: "Weekly Menu",
          path: "/EmployeeWeeklyMeal",
          icon: Layers,
        },
        {
          id: "meal-opt-out",
          label: "Meal Opt-Out",
          path: "/meal-opt-out", // ✅ match App.jsx
          icon: Users,
        },
      ],
    },
    {
      id: "settings",
      label: "Settings",
      path: "/setting",
      icon: Settings,
      submenu: [
        {
          id: "profile",
          label: "Profile",
          path: "/setting",
          icon: CircleUser,
        },
        {
          id: "reset-password",
          label: "Reset Password",
          path: "/reset-password",
          icon: LockKeyholeOpen,
        },
      ],
    },
    {
      id: "messages",
      label: "Chat",
      path: "/chat",
      icon: MessageCircleMore,
    },
  ],
  admin: [
    {
      id: "dashboard",
      label: "Dashboard",
      path: "/dashboard",
      icon: LayoutDashboardIcon,
    },
    {
      id: "attendance",
      label: "Attendance",
      path: "/attendance",
      icon: FileChartColumn,
    },
    {
      id: "employees",
      label: "Employees",
      path: "/employees",
      icon: Users,
    },
    {
      id: "reports",
      label: "Reports",
      path: "/reports",
      icon: ReceiptText,
      submenu: [
        {
          id: "overview",
          label: "Overview",
          path: "/overview",
          icon: ChartNoAxesCombined,
        },
        {
          id: "irregularities",
          label: "Irregularities",
          path: "/irregularities",
          icon: ChartColumnIncreasing,
        },
      ],
    },
    {
      id: "leave",
      label: "Leave",
      path: "/leave",
      icon: TicketsPlane,
      submenu: [
        {
          id: "leave-records",
          label: "Leave Records",
          path: "/leave-records",
          icon: Layers,
        },
        {
          id: "leave-application-history",
          label: "Application History",
          path: "/leave-application-history",
          icon: MailWarning,
        },
        {
          id: "leave-cancelled",
          label: "Leave Cancelled",
          path: "/leave-cancelled",
          icon: XCircle,
        },
      ],
    },
    {
      id: "jobs",
      label: "Jobs",
      path: "/jobs",
      icon: BriefcaseBusiness,
      submenu: [
        {
          id: "job-records",
          label: "Job Records",
          path: "/job-records",
          icon: Layers,
        },
        {
          id: "job-application-history",
          label: "Application History",
          path: "/job-application-history",
          icon: MailWarning,
        },
      ],
    },
    {
      id: "meal",
      label: "Meal",
      path: "/meal",
      icon: Utensils, // import this icon at the top
      submenu: [
        {
          id: "weekly-menu",
          label: "Weekly Menu",
          path: "/meal/weekly",
          icon: Layers,
        },
        {
          id: "meal-override",
          label: "Meal Override",
          path: "/meal/override",
          icon: Layers, // or CalendarDays for visual distinction
        },
        {
          id: "meal-report",
          label: "Meal Report",
          path: "/meal/report",
          icon: FileChartColumn, // Or choose any Lucide icon you like
        },
      ],
    },
    {
      id: "settings",
      label: "Settings",
      path: "/setting",
      icon: Settings,
      submenu: [
        {
          id: "profile",
          label: "Profile",
          path: "/setting",
          icon: CircleUser,
        },
        {
          id: "reset-password",
          label: "Reset Password",
          path: "/reset-password",
          icon: LockKeyholeOpen,
        },
      ],
    },
    // {
    //   id: "messages",
    //   label: "Chat",
    //   path: "/chat",
    //   icon: MessageCircleMore,
    // },
  ],
};

export const ramadanData2026 = [
  {
    ramadan: 1,
    date: "Feb 19",
    day: "Thursday",
    seheri: "5:12 AM",
    iftar: "5:58 PM",
  },
  {
    ramadan: 2,
    date: "Feb 20",
    day: "Friday",
    seheri: "5:11 AM",
    iftar: "5:58 PM",
  },
  {
    ramadan: 3,
    date: "Feb 21",
    day: "Saturday",
    seheri: "5:11 AM",
    iftar: "5:59 PM",
  },
  {
    ramadan: 4,
    date: "Feb 22",
    day: "Sunday",
    seheri: "5:10 AM",
    iftar: "5:59 PM",
  },
  {
    ramadan: 5,
    date: "Feb 23",
    day: "Monday",
    seheri: "5:09 AM",
    iftar: "6:00 PM",
  },
  {
    ramadan: 6,
    date: "Feb 24",
    day: "Tuesday",
    seheri: "5:08 AM",
    iftar: "6:00 PM",
  },
  {
    ramadan: 7,
    date: "Feb 25",
    day: "Wednesday",
    seheri: "5:07 AM",
    iftar: "6:01 PM",
  },
  {
    ramadan: 8,
    date: "Feb 26",
    day: "Thursday",
    seheri: "5:07 AM",
    iftar: "6:01 PM",
  },
  {
    ramadan: 9,
    date: "Feb 27",
    day: "Friday",
    seheri: "5:06 AM",
    iftar: "6:01 PM",
  },
  {
    ramadan: 10,
    date: "Feb 28",
    day: "Saturday",
    seheri: "5:05 AM",
    iftar: "6:02 PM",
  },
  {
    ramadan: 11,
    date: "Mar 01",
    day: "Sunday",
    seheri: "5:04 AM",
    iftar: "6:02 PM",
  },
  {
    ramadan: 12,
    date: "Mar 02",
    day: "Monday",
    seheri: "5:03 AM",
    iftar: "6:03 PM",
  },
  {
    ramadan: 13,
    date: "Mar 03",
    day: "Tuesday",
    seheri: "5:02 AM",
    iftar: "6:03 PM",
  },
  {
    ramadan: 14,
    date: "Mar 04",
    day: "Wednesday",
    seheri: "5:02 AM",
    iftar: "6:04 PM",
  },
  {
    ramadan: 15,
    date: "Mar 05",
    day: "Thursday",
    seheri: "5:01 AM",
    iftar: "6:04 PM",
  },
  {
    ramadan: 16,
    date: "Mar 06",
    day: "Friday",
    seheri: "5:00 AM",
    iftar: "6:05 PM",
  },
  {
    ramadan: 17,
    date: "Mar 07",
    day: "Saturday",
    seheri: "4:59 AM",
    iftar: "6:05 PM",
  },
  {
    ramadan: 18,
    date: "Mar 08",
    day: "Sunday",
    seheri: "4:58 AM",
    iftar: "6:05 PM",
  },
  {
    ramadan: 19,
    date: "Mar 09",
    day: "Monday",
    seheri: "4:57 AM",
    iftar: "6:06 PM",
  },
  {
    ramadan: 20,
    date: "Mar 10",
    day: "Tuesday",
    seheri: "4:56 AM",
    iftar: "6:06 PM",
  },
  {
    ramadan: 21,
    date: "Mar 11",
    day: "Wednesday",
    seheri: "4:55 AM",
    iftar: "6:07 PM",
  },
  {
    ramadan: 22,
    date: "Mar 12",
    day: "Thursday",
    seheri: "4:54 AM",
    iftar: "6:07 PM",
  },
  {
    ramadan: 23,
    date: "Mar 13",
    day: "Friday",
    seheri: "4:53 AM",
    iftar: "6:07 PM",
  },
  {
    ramadan: 24,
    date: "Mar 14",
    day: "Saturday",
    seheri: "4:52 AM",
    iftar: "6:08 PM",
  },
  {
    ramadan: 25,
    date: "Mar 15",
    day: "Sunday",
    seheri: "4:51 AM",
    iftar: "6:08 PM",
  },
  {
    ramadan: 26,
    date: "Mar 16",
    day: "Monday",
    seheri: "4:50 AM",
    iftar: "6:09 PM",
  },
  {
    ramadan: 27,
    date: "Mar 17",
    day: "Tuesday",
    seheri: "4:49 AM",
    iftar: "6:09 PM",
  },
  {
    ramadan: 28,
    date: "Mar 18",
    day: "Wednesday",
    seheri: "4:48 AM",
    iftar: "6:10 PM",
  },
  {
    ramadan: 29,
    date: "Mar 19",
    day: "Thursday",
    seheri: "4:47 AM",
    iftar: "6:10 PM",
  },
  {
    ramadan: 30,
    date: "Mar 20",
    day: "Friday",
    seheri: "4:46 AM",
    iftar: "6:11 PM",
  },
];